separate cases where kubeconfig is used and not used

diff --git a/templates/decapod-apps/remove-lma-uniformed-wftpl.yaml b/templates/decapod-apps/remove-lma-uniformed-wftpl.yaml
--- a/templates/decapod-apps/remove-lma-uniformed-wftpl.yaml
+++ b/templates/decapod-apps/remove-lma-uniformed-wftpl.yaml
@@ -1,4 +1,3 @@
-## Example workflow that calls delete-project template ##
 apiVersion: argoproj.io/v1alpha1
 kind: WorkflowTemplate
 metadata:
@@ -8,10 +7,11 @@ spec:
   entrypoint: process
   arguments:
     parameters:
-    # 'cluster_id' is only for TKS use-case
+    # 'cluster_id' is used for multi-cluster case
+    # Just use default value 'dummy' for single cluster
     # TODO: better to rename this to 'site_name' later
     - name: cluster_id
-      value: ""
+      value: "dummy"
     - name: app_prefix
       value: ""
     # Filter to filter argocd apps
@@ -24,30 +24,49 @@ spec:
         template: disableAutoSync
 
     # Delete prometheus CR first so that it doesn't hang
-    # due to service-account deletion #
+    # due to earlier service-account deletion #
     - - name: removePrometheusCR
         template: removePrometheusCR
         arguments:
           parameters:
           - name: namespace
             value:  "lma"
-          - name: kubeconfig_secret_name
-            value: "{{workflow.parameters.cluster_id}}-kubeconfig"
+        when: "{{=string(workflow.parameters.cluster_id) == 'dummy'}}"
 
-    - - name: removeLMA
-        templateRef:
-          name: delete-apps
-          template: DeleteAppsByLabel
-
-      # LMA appGroup specific task #
-    - - name: cleanupLeftoverResources
-        template: removeLeftoverResources
+    - - name: removePrometheusCrWithKubeconfig
+        template: removePrometheusCrWithKubeconfig
         arguments:
           parameters:
           - name: namespace
             value:  "lma"
           - name: kubeconfig_secret_name
             value: "{{workflow.parameters.cluster_id}}-kubeconfig"
+        when: "{{=string(workflow.parameters.cluster_id) != 'dummy'}}"
+
+    # Remove argo CD apps
+    - - name: removeLMA
+        templateRef:
+          name: delete-apps
+          template: DeleteAppsByLabel
+
+    # Cleanup secrets and PVCs
+    - - name: cleanupLeftoverResources
+        template: removeLeftoverResources
+        arguments:
+          parameters:
+          - name: namespace
+            value:  "lma"
+        when: "{{=string(workflow.parameters.cluster_id) == 'dummy'}}"
+
+    - - name: cleanupLeftoverResourcesWithKubeconfig
+        template: removeLeftoverResourcesWithKubeconfig
+        arguments:
+          parameters:
+          - name: namespace
+            value:  "lma"
+          - name: kubeconfig_secret_name
+            value: "{{workflow.parameters.cluster_id}}-kubeconfig"
+        when: "{{=string(workflow.parameters.cluster_id) != 'dummy'}}"
 
   #######################
   # Template Definition #
@@ -65,6 +84,8 @@ spec:
           if [[ -n "{{workflow.parameters.app_prefix}}" ]]; then
             PROM_APP_NAME="{{workflow.parameters.app_prefix}}-prometheus"
           fi
+          echo "[temp] ARGO_SERVER: $ARGO_SERVER"
+
           # Login to Argo CD server
           ./argocd login $ARGO_SERVER --plaintext --insecure --username $ARGO_USERNAME \
           --password $ARGO_PASSWORD
@@ -81,6 +102,22 @@ spec:
     inputs:
       parameters:
         - name: namespace
+    container:
+      name: remove-prometheus-cr
+      image: k8s.gcr.io/hyperkube:v1.18.6
+      command:
+        - /bin/bash
+        - '-c'
+        - |
+          echo "Deleting prometheus CRs..."
+
+            kubectl delete prometheus --all -n {{inputs.parameters.namespace}}
+            kubectl delete alertmanager --all -n {{inputs.parameters.namespace}}
+
+  - name: removePrometheusCrWithKubeconfig
+    inputs:
+      parameters:
+        - name: namespace
         - name: kubeconfig_secret_name
     container:
       name: remove-prometheus-cr
@@ -92,14 +129,9 @@ spec:
           echo "Deleting prometheus CRs..."
           echo "kubeconfig_secret: {{inputs.parameters.kubeconfig_secret_name}}."
 
-          if [[ -z "{{workflow.parameters.cluster_id}}" ]]; then
-            kubectl delete prometheus --all -n {{inputs.parameters.namespace}}
-            kubectl delete alertmanager --all -n {{inputs.parameters.namespace}}
-          else
             cat <<< "$KUBE_CONFIG" > /etc/kubeconfig
             kubectl --kubeconfig=/etc/kubeconfig delete prometheus --all -n {{inputs.parameters.namespace}}
             kubectl --kubeconfig=/etc/kubeconfig delete alertmanager --all -n {{inputs.parameters.namespace}}
-          fi
       env:
       - name: KUBE_CONFIG
         valueFrom:
@@ -120,14 +152,26 @@ spec:
         - |
           echo "Deleting secrets and PVCs..."
 
-          if [[ -z "{{workflow.parameters.cluster_id}}" ]]; then
-            kubectl delete secret etcd-client-cert prometheus-operator-admission -n {{inputs.parameters.namespace}} || true
-            kubectl delete pvc --all -n {{inputs.parameters.namespace}}
-          else
-            cat <<< "$KUBE_CONFIG" > /etc/kubeconfig
-            kubectl --kubeconfig=/etc/kubeconfig delete secret etcd-client-cert prometheus-operator-admission -n {{inputs.parameters.namespace}} || true
-            kubectl --kubeconfig=/etc/kubeconfig delete pvc --all -n {{inputs.parameters.namespace}}
-          fi
+          kubectl delete secret etcd-client-cert prometheus-operator-admission -n {{inputs.parameters.namespace}} || true
+          kubectl delete pvc --all -n {{inputs.parameters.namespace}}
+
+  - name: removeLeftoverResourcesWithKubeconfig
+    inputs:
+      parameters:
+        - name: namespace
+        - name: kubeconfig_secret_name
+    container:
+      name: remove-leftover
+      image: 'k8s.gcr.io/hyperkube:v1.18.6'
+      command:
+        - /bin/bash
+        - '-c'
+        - |
+          echo "Deleting secrets and PVCs..."
+
+          cat <<< "$KUBE_CONFIG" > /etc/kubeconfig
+          kubectl --kubeconfig=/etc/kubeconfig delete secret etcd-client-cert prometheus-operator-admission -n {{inputs.parameters.namespace}} || true
+          kubectl --kubeconfig=/etc/kubeconfig delete pvc --all -n {{inputs.parameters.namespace}}
       env:
       - name: KUBE_CONFIG
         valueFrom:
